# Generated by Django 4.2.1 on 2024-01-10 13:37

import API.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranSport_API',
            fields=[
                ('transport_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transprot_code', models.CharField(default='bbf388ceb50b7a11', max_length=16)),
                ('transport_name', models.CharField(default='', max_length=2000)),
                ('transport_price', models.FloatField(default=15000)),
                ('weight', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('name_ownerShop', models.CharField(default='', max_length=200)),
                ('name_customer', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000, null=True)),
                ('customer_phone', models.CharField(default='', max_length=20)),
                ('from_district', models.CharField(blank=True, max_length=200)),
                ('from_province', models.CharField(blank=True, max_length=200)),
                ('to_district', models.CharField(blank=True, max_length=200)),
                ('to_province', models.CharField(blank=True, max_length=200)),
                ('post_offices', models.CharField(default='', max_length=2000)),
                ('expected_date', models.DateField(default=API.models.default_expected_date)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
