# Generated by Django 4.2.1 on 2024-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_api',
            name='transport_code',
            field=models.CharField(default='5fd95cb9f24e0d6c', max_length=16),
        ),
    ]
