# Generated by Django 4.2.1 on 2024-01-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_transport_api_transport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_api',
            name='transport_code',
            field=models.CharField(default='045a402c9802d38f', max_length=16),
        ),
    ]
