# Generated by Django 4.2.1 on 2024-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_transport_api_transport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_api',
            name='transport_code',
            field=models.CharField(default='2e0fe31c1dd505e8', max_length=16),
        ),
    ]
