# Generated by Django 4.2.1 on 2024-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_transport_api_transport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_api',
            name='transport_code',
            field=models.CharField(default='e1c5185bcdf605bb', max_length=16),
        ),
    ]
