# Generated by Django 4.2.1 on 2024-01-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_price', models.FloatField(default=0)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_pay', models.CharField(default='123456789', max_length=20)),
                ('account_name', models.CharField(default='Nguyen Van A', max_length=100)),
                ('cvv_pay', models.IntegerField(default='123', max_length=3)),
                ('expiration_month', models.IntegerField(default='12', max_length=2)),
                ('expiration_year', models.IntegerField(default='2024', max_length=4)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, unique=True)),
                ('type', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportByEcm',
            fields=[
                ('from_district', models.CharField(blank=True, max_length=200, null=True)),
                ('from_province', models.CharField(blank=True, max_length=200, null=True)),
                ('to_district', models.CharField(blank=True, max_length=200, null=True)),
                ('to_province', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=400)),
                ('weigth', models.FloatField(default=0)),
                ('from_send', models.CharField(default='', max_length=2000)),
                ('to_send', models.CharField(default='', max_length=2000)),
                ('transport_price', models.FloatField(default=15000)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Shop', 'Shop'), ('Shipper', 'Shipper')], default='Customer', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='account_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='account_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Application.account',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('from_district', models.CharField(blank=True, max_length=200, null=True)),
                ('from_province', models.CharField(blank=True, max_length=200, null=True)),
                ('to_district', models.CharField(blank=True, max_length=200, null=True)),
                ('to_province', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_id', models.UUIDField(primary_key=True, serialize=False)),
                ('weigth', models.FloatField(default=0)),
                ('from_send', models.CharField(default='', max_length=2000)),
                ('to_send', models.CharField(default='', max_length=2000)),
                ('transport_price', models.FloatField(default=15000)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField(default=0)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.product'),
        ),
    ]
