# Generated by Django 4.2.1 on 2024-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_allprovince_alter_payment_cvv_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldistrict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
