# Generated by Django 4.2.1 on 2024-02-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_remove_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
    ]
